import './scss/style.scss';
import './ts/slider';
import './ts/slider-review';
import './ts/calc';
import './ts/modals';
import './ts/setup-forms';
import './ts/scroll';
import './ts/f5leads-init';
import './ts/f5leads';
